class item():
    def __init__(self,item,quantite):
        self.dico_item={"Pierre":{"u":0,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Gel_bleu":{"u":8,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Fer":{"u":16,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Gel_rose":{"u":32,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Gel_desert":{"u":40,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Gel_givre":{"u":48,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Gel_rouge":{"u":56,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Glace":{"u":64,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Cactus":{"u":72,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Porc":{"u":80,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Eau":{"u":88,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Pomme":{"u":96,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Oeil_slime":{"u":112,"v":245,"quantite_max":99,"image":2,"type":"invocation"},
                        "Glace_choco":{"u":120,"v":245,"quantite_max":99,"image":2,"type":"invocation"},
                        "Catapeche":{"u":128,"v":245,"quantite_max":99,"image":2,"type":"invocation"},
                        "Porc_de_lave":{"u":144,"v":245,"quantite_max":99,"image":2,"type":"invocation"},
                        "Sus":{"u":152,"v":245,"quantite_max":99,"image":2,"type":"invocation"},
                        "Pyramide":{"u":104,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Fragment_epee":{"u":1,"v":115,"quantite_max":99,"image":0,"type":"materiaux"},
                        "Pierre_de_lave":{"u":136,"v":245,"quantite_max":99,"image":2,"type":"materiaux"},
                        "Epee_pierre":{"u":1,"v":232,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_givre":{"u":1,"v":222,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_bois":{"u":1,"v":242,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_slime":{"u":1,"v":212,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_grosse":{"u":17,"v":202,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_slime_rose":{"u":1,"v":201,"quantite_max":1,"image":0,"type":"epee"},
                        "Grosse_epee_slime":{"u":1,"v":188,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_magique":{"u":1,"v":175,"quantite_max":1,"image":0,"type":"epee"},
                        "Veritable_epee_magique":{"u":1,"v":165,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_mecanique":{"u":1,"v":155,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_mecasus":{"u":1,"v":145,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_sus":{"u":1,"v":135,"quantite_max":1,"image":0,"type":"epee"},
                        "Epee_ultime":{"u":1,"v":125,"quantite_max":1,"image":0,"type":"epee"},
                        "Potion":{"u":24,"v":245,"quantite_max":99,"image":2,"type":"potion"},
                        "Coeur":{"u":8,"v":0,"quantite_max":1,"image":2,"type":"coeur"},
                        "None": {"u":1,"v":232,"quantite_max":1,"image":0,"type":"None"}}
        self.u=self.dico_item[item]["u"]
        self.v=self.dico_item[item]["v"]
        self.item=item
        self.w=8
        self.h=10
        self.quantite=quantite
        self.quantite_max=self.dico_item[item]["quantite_max"]
        self.image=self.dico_item[item]["image"]
        self.x=0
        self.y=0
        self.type=self.dico_item[item]["type"]
